services:
  proxy:
    image: nginx:alpine3.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    image: ghcr.io/mbank/frontend:dev

  api-gateway:
    image: ghcr.io/mbank/api-gateway:dev
    environment:
      - ACCOUNT_SERVICE_HOST=account-service
      - ACCOUNT_SERVICE_PORT=3001

  account-service:
    image: ghcr.io/mbank/account-service:dev
    environment:
      - TRANSACTION_SERVICE_HOST=transaction-service
      - TRANSACTION_SERVICE_PORT=3002

  transaction-service:
    image: ghcr.io/mbank/transaction-service:dev