services:
  reverse-proxy:
    image: ghcr.io/mbank/reverse-proxy:dev
    container_name: reverse-proxy
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    ports:
      - "80:80"

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1@sha256:9869b88191392727f0be7301e53573cc39c13c9d9b9b08492c97d1ea40366eae
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_DB_URL: jdbc:postgresql://db/${POSTGRES_KC_DB}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HTTP_RELATIVE_PATH: /auth
      KC_SPI_AUTHENTICATOR_REGISTER_WITH_BALANCE_USER_SERVICE_URL: http://api-gateway:${API_GATEWAY_PORT}/webhook/keycloak
      # KC_SPI_AUTHENTICATOR_REGISTER_WITH_BALANCE_USER_SERVICE_URL: http://host.docker.internal:3000/webhook/keycloak
    ports:
      - "8080:8080"
    command: ["start", "--import-realm", "--http-enabled=true"]
    volumes:
      - ../apps/keycloak/realms:/opt/keycloak/data/import
      - ../apps/keycloak/providers/keycloak-authenticator.jar:/opt/keycloak/providers/keycloak-authenticator.jar
      - ../apps/keycloak/themes:/opt/keycloak/themes

  frontend:
    image: ghcr.io/mbank/frontend:dev
    container_name: frontend

  api-gateway:
    image: ghcr.io/mbank/api-gateway:dev
    container_name: api-gateway
    environment:
      - PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}

  user-service:
    image: ghcr.io/mbank/user-service:dev
    container_name: user-service
    environment:
      - PORT=${USER_SERVICE_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER_SERVICE_DB}?schema=public

  db:
    image: postgres:16.8-alpine3.21@sha256:3b057e1c2c6dfee60a30950096f3fab33be141dbb0fdd7af3d477083de94166c
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
