services:
  reverse-proxy:
    image: ghcr.io/mbank/reverse-proxy:dev
    ports:
      - "80:80"
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}

  frontend:
    image: ghcr.io/mbank/frontend:dev

  api-gateway:
    image: ghcr.io/mbank/api-gateway:dev
    environment:
      - PORT=${API_GATEWAY_PORT}
      - ACCOUNT_SERVICE_HOST=account-service
      - ACCOUNT_SERVICE_PORT=${ACCOUNT_SERVICE_PORT}

  account-service:
    image: ghcr.io/mbank/account-service:dev
    environment:
      - PORT=${ACCOUNT_SERVICE_PORT}
      - TRANSACTION_SERVICE_HOST=transaction-service
      - TRANSACTION_SERVICE_PORT=${TRANSACTIONS_SERVICE_PORT}

  transaction-service:
    image: ghcr.io/mbank/transaction-service:dev
    environment:
      - PORT=${TRANSACTIONS_SERVICE_PORT}