# k8s/account-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: ghcr.io/mbank/account-service:dev
          ports:
            - containerPort: 3001
          env:
            - name: TRANSACTION_SERVICE_HOST
              value: "transaction-service" # имя сервиса внутри кластера
            - name: TRANSACTION_SERVICE_PORT
              value: "3002"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - port: 3001
      targetPort: 3001
