# k8s/proxy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: nginx:alpine3.19
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: proxy-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: NodePort # на minikube можно использовать NodePort для доступа извне
  selector:
    app: proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
