apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: ghcr.io/mbank/reverse-proxy:dev
          env:
            - name: API_GATEWAY_PORT
              value: "3000"   # or whatever ${API_GATEWAY_PORT} is
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: NodePort
  selector:
    app: reverse-proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
